<?php

/**
 * @file
 * MessageBird module file.
 */

/**
 * Implements hook_menu().
 */
function messagebird_menu() {

  $items['admin/config/services/messagebird'] = array(
    'title' => 'MessageBird',
    'description' => 'Configure MessageBird settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('messagebird_settings_form'),
    'access arguments' => array('administer messagebird'),
    'file' => 'messagebird.admin.inc',
  );

  $items['admin/config/services/messagebird/settings'] = array(
    'title' => 'Settings',
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );

  $items['admin/config/services/messagebird/send'] = array(
    'title' => 'Send a message',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('messagebird_send_form'),
    'access arguments' => array('administer messagebird'),
    'file' => 'messagebird.admin.inc',
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function messagebird_permission() {
  return array(
    'administer messagebird' => array(
      'title' => t('Administer MessageBird'),
      'description' => t('Perform administration tasks for MessageBird.'),
    ),
  );
}

/**
 * Implements hook_libraries_info().
 */
function messagebird_libraries_info() {
  $libraries['messagebird'] = array(
    'name' => 'MessageBird API',
    'vendor url' => 'https://www.messagebird.com/developers/php',
    'download url' => 'https://github.com/messagebird/php-rest-api/archive/master.zip',
    'version arguments' => array(
      'file' => 'composer.json',
      'pattern' => '/(\d\.\d\.\d)/',
      'lines' => 10,
    ),
    'files' => array(
      'php' => array(
        'autoload.php',
      ),
    ),
  );

  return $libraries;
}

/**
 * Send a message through the MessageBird API.
 *
 * @param $body
 *   The message to send.
 * @param $recipients
 *   An array of recipients.
 * @param $originator
 *   The sender of the message, having a maximum of 11 characters.
 * @param $options
 *   An array of optional parameters, for more information:
 *   https://www.messagebird.com/en/developers#messaging-send
 */
function messagebird_send($body, $recipients, $originator = NULL, $options = array()) {
  $library = libraries_load('messagebird');

  if (!$library['installed']) {
    watchdog('messagebird', 'Could not locate MessageBird library');
    return FALSE;
  }

  $api_key = variable_get('messagebird_api_key', '');

  if (!is_array($recipients)) {
    $recipients = array($recipients);
  }

  if (!$originator) {
    $originator = variable_get('messagebird_default_originator', '');
  }

  $debug_mode = variable_get('messagebird_debug_mode', 0);
  if ($debug_mode) {
    $debug_params = array(
      'Body: ' . check_plain($body),
      'Recipients: ' . check_plain(implode(', ', $recipients)),
      'Originator: ' . check_plain($originator),
    );
    drupal_set_message(theme('item_list', array('items' => $debug_params)));
  }

  $MessageBird = new \MessageBird\Client($api_key);

  $message = new \MessageBird\Objects\Message();
  $message->originator = $originator;
  $message->recipients = $recipients;
  $message->body = $body;

  // Append the optional parameters.
  foreach ($options as $parameter => $value) {
    if (!empty($parameter) && !empty($value)) {
      $message->{$parameter} = $value;
    }
  }

  try {
    // Send the message to the recipient(s).
    $response = $MessageBird->messages->create($message);

    return $response;
  }
  catch (\MessageBird\Exceptions\AuthenticateException $e) {
    // Authentication failed. Is this a wrong access_key?
    watchdog(
      'messagebird',
      'Message sending failed due to an authentication exception. Error message: @error_message',
      array('@error_message' => $e->getMessage()),
      WATCHDOG_ERROR,
      l(t('Settings'), 'admin/config/services/messagebird')
    );
  }
  catch (\MessageBird\Exceptions\BalanceException $e) {
    // That means that you are out of credits. Only called on creation of a object.
    watchdog(
      'messagebird',
      'Message sending failed due to a shortage of credits. Error message: @error_message',
      array('@error_message' => $e->getMessage()),
      WATCHDOG_ERROR,
      l(t('Settings'), 'admin/config/services/messagebird')
    );
  }
  catch (\Exception $e) {
    // Request failed. More information can be found in the body.
    watchdog(
      'messagebird',
      'Message sending failed due to an unexpected exception. Error message: @error_message',
      array('@error_message' => $e->getMessage()),
      WATCHDOG_ERROR,
      l(t('Settings'), 'admin/config/services/messagebird')
    );
  }

  return FALSE;
}
